services:
  spot-recommendation-redis:
    container_name: spot-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: dockerosw/spot-recommendation-redis
    ports:
      - "6379:6379"

  spot-recommendation-database:
    container_name: spot-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: dockerosw/spot-recommendation-database
    environment:
      - MARIADB_DATABASE=spot-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"


